### ISSUE TITLE
The example cannot be build as the hello package not found.

### ISSUE THREAD

**Issue by forlayo** [memsharded/qmake_example#1]
I'm not sure if that's a real issue or that's not the purpose of the example, but it cannot build as the package doesn't exist.

```
mike@ultramike:~/workspace/conanstuff$ cd qmake_example/
mike@ultramike:~/workspace/conanstuff/qmake_example$ conan install
Hello/0.1@diego/testing: Not found, looking in remotes...
WARN: Remotes registry file missing, creating default one in /home/mike/.conan/registry.txt
Hello/0.1@diego/testing: Trying with 'conan.io'...
ERROR: Unable to find 'Hello/0.1@diego/testing' in remotes
mike@ultramike:~/workspace/conanstuff/qmake_example$ cat /home/mike/.con
.conan/  .config/ 
mike@ultramike:~/workspace/conanstuff/qmake_example$ cat /home/mike/.conan/registry.txt
conan.io https://server.conan.io True
mike@ultramike:~/workspace/conanstuff/qmake_example$ conan install
Hello/0.1@diego/testing: Not found, looking in remotes...
Hello/0.1@diego/testing: Trying with 'conan.io'...
ERROR: Unable to find 'Hello/0.1@diego/testing' in remotes
```

**Comment by memsharded** [comment]
Have you followed first the instructions in: https://github.com/memsharded/hello_multi_config ?

That would install the hello package locally.

**Comment by forlayo** [comment]
@memsharded sorry I've missed that point that creates the local package :(. Now it works, thanks!

**Comment by memsharded** [comment]
No worries, glad it worked now :)

**Comment by forlayo** [comment]
@memsharded I continue having problems I don't know where they comes, can you please bring me some light ?

Also in general I'm a bit confused on how to set up my project with this kind of integration, this is generating a .pri to include the dependency on a Qt project but doesn't exposes how to create a library that's a Qt library project then create a package from it to being consumed on other projects; and most of examples I'm seeing are focused on using CMake not qmake. 

Are there documentation about this usage ? Sorry about using this channel for asking.

Problem I'm getting with the step of "make"
```
mike@ultramike:~/workspace/conanstuff/qmake_example$ conan install
Requirements
    Hello/0.1@diego/testing from local
Packages
    Hello/0.1@diego/testing:991c2f2c4cec0520057a7a6996955725136eaf4b

Hello/0.1@diego/testing: Already installed!
PROJECT: Generated qmake created conanbuildinfo.pri
PROJECT: Generated conaninfo.txt
mike@ultramike:~/workspace/conanstuff/qmake_example$ ls
conanbuildinfo.pri  conaninfo.txt  main.cpp  Makefile     README.md
conanfile.txt       LICENSE        main.o    project.pro
mike@ultramike:~/workspace/conanstuff/qmake_example$ make clean
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake CONFIG+=debug -o Makefile project.pro
rm -f main.o
rm -f *~ core *.core
mike@ultramike:~/workspace/conanstuff/qmake_example$ ls
conanbuildinfo.pri  conanfile.txt  conaninfo.txt  LICENSE  main.cpp  Makefile  project.pro  README.md
mike@ultramike:~/workspace/conanstuff/qmake_example$ qmake
mike@ultramike:~/workspace/conanstuff/qmake_example$ make
g++ -c -m64 -pipe -O2 -Wall -W -fPIC  -I. -I../../../.conan/data/Hello/0.1/diego/testing/package/991c2f2c4cec0520057a7a6996955725136eaf4b/include -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o main.cpp
g++ -m64 -Wl,-O1 -o helloworld main.o   -L/home/mike/.conan/data/Hello/0.1/diego/testing/package/991c2f2c4cec0520057a7a6996955725136eaf4b/lib 
main.o: In function `main':
main.cpp:(.text.startup+0x5): undefined reference to `hello()'
collect2: error: ld returned 1 exit status
Makefile:133: recipe for target 'helloworld' failed
make: *** [helloworld] Error 1
```

**Comment by memsharded** [comment]
Hi Miguel,

No worries, this channel is fine for asking.

Not sure about your question though. Is that error produced when running the examples, following the exact steps of the instructions? It seems that you are not adding the libraries defined in conanbuildinfo.pri to your binaries in your project .pro file.

Not sure also about the question on how to create a library. Conan is not a build system, it is a package manager. The one defining how to create a library is the build system, in this case qmake. Then, conan wraps it, calling it to do the actual build, then packages the final artifacts. Finally, conan exposes to the package consumers, in their respective build system the interface to the required dependencies/packages.

Please tell me, and I will try to help :)

Best regards
